version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
      - deploy
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      # - run:
      #     name: Run tests
      #     command: pipenv run pytest
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - SHA256:Bivx51+6wDszMWTX3Gy/7O+zhYtIZsnH8kSe1agT5N4
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote-deploy-command>"