# version: 2
# jobs:
#   build:
#     docker:
#       - image: cimg/python:3.8
#   deploy:
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - SHA256:d+6W3EBUQe9cC7cLwctwyIxwMu5O5v989ASL+k1FBKk
#       - checkout
#       - python/install-packages:
#           pkg-manager: pipenv
#       - run:
#           name: Deploy Over SSH
#           command: |
#             ssh $SSH_USER@$SSH_HOST "<remote-deploy-command>"

# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: main



version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      # - run:
      #     name: Run tests
      #     command: pipenv run pytest
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - SHA256:d+6W3EBUQe9cC7cLwctwyIxwMu5O5v989ASL+k1FBKk
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote-deploy-command>"